// src/components/DesktopHomepageNotLoggedIn/WebsiteHomePageNotLoggedIn.vue
<template>
  <div class="container-center-horizontal">
    <div class="website-home-page-not-logged-in screen">
      <div class="overlap-group3" :style="{ 'background-image': 'url(' + overlapGroup3 + ')' }">
        <weather :text1="weatherProps.text1" :h50L40="weatherProps.h50L40" :place="weatherProps.place" />
        <input-search :inputType="inputSearchProps.inputType" :inputPlaceholder="inputSearchProps.inputPlaceholder" />
        <div class="weather-for-today">
          <weather-throughout-the-day
            :now1Props="weatherThroughoutTheDay1Props.now1Props"
            :now2Props="weatherThroughoutTheDay1Props.now2Props"
            :now3Props="weatherThroughoutTheDay1Props.now3Props"
          />
          <weather-throughout-the-day
            :now1Props="weatherThroughoutTheDay2Props.now1Props"
            :now2Props="weatherThroughoutTheDay2Props.now2Props"
            :now3Props="weatherThroughoutTheDay2Props.now3Props"
          />
          <weather-throughout-the-day
            :now1Props="weatherThroughoutTheDay3Props.now1Props"
            :now2Props="weatherThroughoutTheDay3Props.now2Props"
            :now3Props="weatherThroughoutTheDay3Props.now3Props"
          />
        </div>
        <div class="flex-row-4">
          <ellipse64 />
          <img
            class="vector-4"
            src="https://anima-uploads.s3.amazonaws.com/projects/6402851d6a37db7167320ed4/releases/64028608c9953e08464983be/img/vector-1.svg"
            alt="Vector"
          />
        </div>
        <img class="home-logo-2" :src="homeLogo2" alt="Home Logo 2" />
        <div class="frame-7">
          <img
            class="vector-5"
            src="https://anima-uploads.s3.amazonaws.com/projects/6402851d6a37db7167320ed4/releases/64028608c9953e08464983be/img/vector.svg"
            alt="Vector"
          />
          <h1 class="login-to-view-a-pers">{{ loginToViewAPers }}</h1>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Weather from "./Weather";
import InputSearch from "./InputSearch";
import WeatherThroughoutTheDay from "./WeatherThroughoutTheDay";
import Ellipse64 from "./Ellipse64";
export default {
  name: "WebsiteHomePageNotLoggedIn",
  components: {
    Weather,
    InputSearch,
    WeatherThroughoutTheDay,
    Ellipse64,
  },
  props: [
    "overlapGroup3",
    "homeLogo2",
    "loginToViewAPers",
    "weatherProps",
    "inputSearchProps",
    "weatherThroughoutTheDay1Props",
    "weatherThroughoutTheDay2Props",
    "weatherThroughoutTheDay3Props",
  ],
};
</script>

<style>

.website-home-page-not-logged-in {
  align-items: flex-start;
  background-color: var(--white);
  border: 1px none;
  display: flex;
  min-height: 100vh;
  padding: 25px;
}

.overlap-group3 {
  align-items: center;
  background-position: 50% 50%;
  background-size: cover;
  height: 100%;
  background-repeat: no-repeat;
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  min-width: 1024px;
}

.weather-for-today {
  align-items: flex-start;
  display: flex;
  height: 104px;
  left: 353px;
  position: absolute;
  top: 663px;
  width: 693px;
}

.flex-row-4 {
  align-items: center;
  display: flex;
  gap: 38px;
  height: 50px;
  left: 1181px;
  min-width: 129px;
  position: absolute;
  top: 58px;
}

.vector-4 {
  height: 41px;
  margin-bottom: 1px;
  width: 41px;
}

.home-logo-2 {
  height: 51px;
  left: 68px;
  object-fit: cover;
  position: absolute;
  top: 57px;
  width: 192px;
}

.frame-7 {
  height: 312px;
  left: 559px;
  position: absolute;
  top: 312px;
  width: 442px;
}

.vector-5 {
  height: 292px;
  left: 10px;
  position: absolute;
  top: 10px;
  width: 431px;
}

.login-to-view-a-pers {
  color: #000000bf;
  font-family: var(--font-family-inter);
  font-size: var(--font-size-xxxxl);
  font-weight: 400;
  left: 20px;
  letter-spacing: 0;
  line-height: normal;
  position: absolute;
  text-align: center;
  top: 66px;
  width: 420px;
}
</style>

// components/WebsiteHomePageNotLoggedIn/index.jsx
import React from "react";
import InputSearch from "../InputSearch";
import Weather from "../Weather";
import OutfitOfTheDay from "../OutfitOfTheDay";
import WeatherThroughoutTheDay from "../WeatherThroughoutTheDay";
import Ellipse6 from "../Ellipse6";
import "./WebsiteHomePageNotLoggedIn.css";

class WebsiteHomePageNotLoggedIn extends React.Component {
  render() {
    const {
      overlapGroup3,
      homeLogo2,
      loginToViewAPers,
      inputSearchProps,
      weatherProps,
      outfitOfTheDayProps,
      weatherThroughoutTheDay1Props,
      weatherThroughoutTheDay2Props,
      weatherThroughoutTheDay3Props,
    } = this.props;

    return (
      <div className="container-center-horizontal">
        <div className="website-home-page-not-logged-in screen">
          <div className="overlap-group3" style={{ backgroundImage: `url(${overlapGroup3})` }}>
            <img className="home-logo-2" src={homeLogo2} alt="Home Logo 2" />
            <div className="flex-col">
              <InputSearch
                inputSearch={inputSearchProps.inputSearch}
                inputType={inputSearchProps.inputType}
                inputPlaceholder={inputSearchProps.inputPlaceholder}
              />
              <div className="flex-row">
                <Weather place={weatherProps.place} text1={weatherProps.text1} h50L40={weatherProps.h50L40} />
                <div className="overlap-group4">
                  <OutfitOfTheDay
                    outfitOfTheDay={outfitOfTheDayProps.outfitOfTheDay}
                    line81={outfitOfTheDayProps.line81}
                    line82={outfitOfTheDayProps.line82}
                    spanText={outfitOfTheDayProps.spanText}
                  />
                  <div className="rectangle-263"></div>
                  <h1 className="login-to-view-a-pers">{loginToViewAPers}</h1>
                </div>
              </div>
              <div className="weather-for-today">
                <WeatherThroughoutTheDay
                  now1Props={weatherThroughoutTheDay1Props.now1Props}
                  now2Props={weatherThroughoutTheDay1Props.now2Props}
                  now3Props={weatherThroughoutTheDay1Props.now3Props}
                />
                <WeatherThroughoutTheDay
                  now1Props={weatherThroughoutTheDay2Props.now1Props}
                  now2Props={weatherThroughoutTheDay2Props.now2Props}
                  now3Props={weatherThroughoutTheDay2Props.now3Props}
                />
                <WeatherThroughoutTheDay
                  now1Props={weatherThroughoutTheDay3Props.now1Props}
                  now2Props={weatherThroughoutTheDay3Props.now2Props}
                  now3Props={weatherThroughoutTheDay3Props.now3Props}
                />
              </div>
            </div>
            <Ellipse6 />
            <img className="vector" src="/img/vector@2x.png" alt="Vector" />
          </div>
        </div>
      </div>
    );
  }
}

export default WebsiteHomePageNotLoggedIn;
