// src/components/DesktopHomepageNotLoggedIn/WeatherThroughoutTheDay.vue
<template>
    <article class="weather-throughout-the-day">
      <div class="flex-row-5">
        <now :now="now1Props.now" :className="now1Props.className" />
        <now :now="now2Props.now" :className="now2Props.className" />
        <now :now="now3Props.now" :className="now3Props.className" />
      </div>
    </article>
  </template>
  
  <script>
  import Now from "./Now";
  export default {
    name: "WeatherThroughoutTheDay",
    components: {
      Now,
    },
    props: ["now1Props", "now2Props", "now3Props"],
  };
  </script>
  
  <style>
  .weather-throughout-the-day {
    height: 104px;
    min-width: 216px;
    position: relative;
  }
  .flex-row-5 {
    align-items: flex-start;
    display: flex;
    height: 104px;
    min-width: 216px;
    position: relative;
  }
  </style>

// components/WeatherThroughoutTheDay/index.jsx
import React from "react";
import Now from "../Now";
import "./WeatherThroughoutTheDay.css";

class WeatherThroughoutTheDay extends React.Component {
  render() {
    const { now1Props, now2Props, now3Props } = this.props;

    return (
      <article className="weather-throughout-the-day">
        <Now now={now1Props.now} className={now1Props.className} />
        <Now now={now2Props.now} className={now2Props.className} />
        <Now now={now3Props.now} className={now3Props.className} />
      </article>
    );
  }
}

export default WeatherThroughoutTheDay;
